channels:
  anthonywritescode: UC46xhU1EH7aywEgvA9syS3w
  ArjanCodes: UCVhQ2NnY5Rskt6UjCUkJ_DA
  Beyond Fireship: UC2Xd-TjJByJyK2w1zNwY0zQ
  ByteByteGo: UCZgt6AzoyjslHTC9dz0UoTw
  Christian Lempa: UCZNhwA1B5YqiY1nLzmM0ZRg
  Cloud Native Computing Foundation: UCvqbFHwN-nwalWPjPUKpvTA
  CloudHeroes - Video: UCymCJotX9RRQjgdAzNzoZsQ
  Computerphile: UC9-y-6csu5WGm29I7JiwpnA
  Corey Schafer: UCCezIgC97PvUuR4_gbFUs5g
  DevOps Toolbox: UCYeiozh-4QwuC1sjgCmB92w
  Eric Roby: UCFxwS8HIGH5_ut1fk0PNAHw
  Fireship: UCsBjURrPoezykLs9EqgamOA
  GitHub: UC7c3Kb6jYCRj4JOHHZTxKsQ
  hello roman: UCq8XmOMtrUCb8FcFHQEd8_g
  Jeremy Howard: UCX7Y2qWriXpqocG97SFW2OQ
  Justin Sung: UC2Zs9v2hL2qZZ7vsAENsg4w
  Mateusz Chrobok: UCTTZqMWBvLsUYqYwKTdjvkw
  "Maximilian Schwarzm\xFCller": UCNxUdsuH8-kEGIwSD0r8RhQ
  "Maximilian Schwarzm\xFCller Ext.": UCzgpZFMMLOew2u0x2BvhsXw
  mCoding: UCaiL2GDNpLYH6Wokkk1VNcg
  MongoDB: UCK_m2976Yvbx-TyDLw7n1WA
  Nicole van der Hoeven: UCrmQZ9HHnJ2qpd6udc8iYYw
  OpenAI: UCXZCJLdBC09xxGZ6gcdrc6A
  Postman: UCocudCGVb3MmhWQ1aoIgUQw
  Real Python: UCI0vQvr9aFn27yR6Ej6n5UA
  SysOps / DevOps Polska: UCQ8D7kwvZJxQdy70vYZCf7w
  Tech With Tim: UC4JX40jDee_tINbkjycV4Sg
  ThePrimeagen: UC8ENHE5xdFSwx71u3fDH5Xw
  TJ DeVries: UCd3dNckv1Za2coSaHGHl5aA
  Visual Studio Code: UCs5Y5_7XK8HLDX0SLNwkd3w
  What The Func? w/ Ed Zynda: UC0Wu-J4_SoFOYVKA8JRuRRg
results: 10
